set nocompatible              " be iMproved, required
filetype off                  " required

" Vundle Start
" ------------
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle Plugins
" --------------
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
if has('unix')
  if has('mac')
    Plugin 'Valloric/YouCompleteMe'
    Plugin 'gilligan/vim-lldb'
  end
end
Plugin 'bling/vim-airline'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-rake'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'L9'
Plugin 'wincent/command-t'
Plugin 'idanarye/vim-vebugger'

" Vundle Themes
" -------------
Plugin 'gosukiwi/vim-atom-dark'
Plugin 'tomasr/molokai'
Plugin 'joshdick/onedark.vim'
Plugin 'fxn/vim-monochrome'
Plugin 'xero/blaquemagick.vim'

" Vundle End
" ----------
call vundle#end()            " required
filetype plugin indent on    " required

let &t_Co=256
syntax enable
colorscheme blaquemagick 

" Formatting And Settings
" -----------------------
set backspace=2
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set number
set linespace=1
set mouse=a
set cursorline
set colorcolumn=81
set laststatus=2
let g:airline#extensions#tabline#enabled = 1
set list
set listchars=tab:»\ ,eol:¬
autocmd VimResized * wincmd =


" Clipboard
" ---------
set clipboard=unnamed

" Powerline
" ---------
let g:airline_powerline_fonts=1
set guifont=Liberation\ Mono\ for\ Powerline\ 10

" YCM
" ---
"let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'

" NerdTree
" --------
let NERDTreeShowHidden=1

