# Git branch in prompt.
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\$(parse_git_branch)\[\033[m\]\$ "
export GREP_OPTIONS='--color=always -n'
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export DYLD_LIBRARY_PATH=./
export QT_HOME=~/Qt/5.6
export NDK=~/Library/Android/sdk/ndk-bundle
